### ISSUE TITLE
Djando 的动态model

### ISSUE THREAD

**Issue by mattshma** [mattshma/omega#3]
情景：因为表太大，所以在设计时将表设计为日表，表名为tb_monitor_YYYYmmdd。直接使用Mysqldb模块来操作的话，是比较简单的，但使用django的orm呢？

django 不能在meodel的meta中指定表名。那怎样满足以上要求呢？

**Comment by beitian** [comment]
参考：

- [Django dynamic model fields](http://stackoverflow.com/questions/7933596/django-dynamic-model-fields/7934577#7934577)
- [Dynamic models](https://code.djangoproject.com/wiki/DynamicModels#Thebasictechnique)
